# F1 Prediction System Configuration v3.0

# Model Configuration
model:
  default_type: "ensemble"
  algorithms:
    - "lightgbm"
    - "xgboost" 
    - "random_forest"
    - "neural_network"
  
  # Ensemble weights (auto-optimized if null)
  ensemble_weights:
    lightgbm: 0.30
    xgboost: 0.25
    random_forest: 0.20
    neural_network: 0.25
  
  # LightGBM parameters
  lightgbm:
    objective: "regression"
    metric: "mae"
    boosting_type: "gbdt"
    n_estimators: 3000
    learning_rate: 0.015
    max_depth: 10
    num_leaves: 127
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 7
    min_child_samples: 25
    min_split_gain: 0.01
    reg_alpha: 0.15
    reg_lambda: 0.25
    random_state: 42
    n_jobs: -1
    verbose: -1
    early_stopping_rounds: 200
  
  # XGBoost parameters
  xgboost:
    objective: "reg:absoluteerror"
    eval_metric: "mae"
    n_estimators: 3000
    learning_rate: 0.015
    max_depth: 10
    colsample_bytree: 0.8
    subsample: 0.8
    min_child_weight: 25
    alpha: 0.15
    lambda: 0.25
    random_state: 42
    n_jobs: -1
    verbosity: 0
    tree_method: "hist"
    early_stopping_rounds: 200

# Feature Engineering Configuration
features:
  rolling_windows:
    short: 3
    medium: 5
    long: 10
    season: 23
  
  circuit_categories:
    street: ["Monaco", "Singapore", "Baku", "Las Vegas", "Miami", "Jeddah"]
    high_speed: ["Monza", "Spa-Francorchamps", "Silverstone", "Suzuka", "Bahrain"]
    technical: ["Monaco", "Singapore", "Hungary", "Spain", "Abu Dhabi"]
    power_sensitive: ["Monza", "Spa-Francorchamps", "Baku", "Las Vegas"]
    aero_sensitive: ["Monaco", "Singapore", "Hungary", "Spain"]
  
  min_data_requirements:
    driver_features: 5
    team_features: 3
    circuit_features: 2
  
  correlation_threshold: 0.95
  max_features_selection: 50

# Data Collection Configuration
data:
  start_year: 2018
  current_season: 2025
  
  # API settings
  api:
    fetch_delay: 1.5
    retry_delay: 60
    max_retries: 5
    timeout_seconds: 45
    cache_expiry_hours: 24
  
  # Database settings
  database:
    type: "duckdb"
    path: "f1_data_real/f1_prediction.db"
    backup_enabled: true

# Training Configuration
training:
  test_size: 0.15
  validation_size: 0.15
  cv_folds: 7
  random_state: 42
  
  # Optimization
  hyperparameter_optimization:
    enabled: true
    n_trials: 150
    timeout_hours: 4
    metric: "mae"
    direction: "minimize"
  
  # Early stopping
  early_stopping:
    rounds: 250
    metric: "mae"
    tolerance: 1e-6

# Prediction Configuration
prediction:
  confidence_thresholds:
    very_high: 0.9
    high: 0.8
    medium: 0.6
    low: 0.4
    very_low: 0.2
  
  imputation_defaults:
    grid_pos: 15.0
    quali_pos: 15.0
    driver_avg_finish: 12.0
    team_avg_finish: 12.0
    weather_temp: 25.0
    weather_humidity: 60.0

# MLflow Configuration
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "f1_prediction_v3"
  log_models: true
  log_artifacts: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
  file_path: "logs/f1_predictor.log"
  max_file_size_mb: 100
  backup_count: 5

# Performance Configuration
performance:
  use_polars: true
  parallel_processing: true
  memory_optimization: true
  cache_features: true
  max_memory_gb: 8
  n_jobs: -1
  chunk_size: 10000 